### ISSUE TITLE
Different alignment between local dev and published version

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/docs#101] opened 2020-02-12 08:32 UTC
I don't have the same alignment on the homepage from the local dev version and the one publish on docs.mesg.com

I think the local version is the correct

local:
<img width="1055" alt="Screen Shot 2020-02-12 at 15 29 54" src="https://user-images.githubusercontent.com/5823445/74316694-981d6b80-4dac-11ea-861c-ef109f2ff207.png">

published:
<img width="1055" alt="Screen Shot 2020-02-12 at 15 29 45" src="https://user-images.githubusercontent.com/5823445/74316701-9bb0f280-4dac-11ea-8185-1aebdb9ce239.png">

that's not only on the homepage:
local:
<img width="1042" alt="Screen Shot 2020-02-12 at 15 31 28" src="https://user-images.githubusercontent.com/5823445/74316793-d1ee7200-4dac-11ea-975d-43d54b295ab4.png">

published:
<img width="1042" alt="Screen Shot 2020-02-12 at 15 31 34" src="https://user-images.githubusercontent.com/5823445/74316802-d4e96280-4dac-11ea-807e-95040fe5762e.png">

**Comment by antho1404** [comment] 2020-02-12 13:10
can't reproduce, can you make sure you have the latest version and your packages are up to date. Remove your `node_modules` and run `npm install` again and this should work.

**Comment by NicolasMahe** [comment] 2020-02-14 10:45
I deleted `node_module` and reinstalled and my local version has the correct alignment.
Maybe it's netlify that keep in cache some stuff and break the alignment?

**Comment by NicolasMahe** [comment] 2020-02-14 10:57
the issue appears when the website is built with `npm run build`, not with `npm run dev`.

**Comment by NicolasMahe** [comment] 2020-02-14 11:05
it seems to come from this css property:
https://github.com/mesg-foundation/docs/blob/7bdc74f7f84936e11ed21b077796c776957e6b4f/.vuepress/components/param-table.vue#L90-L92

maybe the `<style scopped>` doesn't work properly when built?

**Comment by antho1404** [comment] 2020-02-15 02:37
nice catch, I just pushed a fix

**Closed as completed by antho1404** 2020-02-15 02:37 UTC
Labels: bug
